# Generated by Django 2.0.7 on 2018-07-14 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ref',
            field=models.TextField(default=uuid.UUID('241a4b98-73bf-4941-a841-e2cf3fc25fcb')),
        ),
    ]
