# Generated by Django 2.0.7 on 2018-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_component', '0003_auto_20180714_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ref',
            field=models.TextField(blank=True, default=''),
        ),
    ]
